export const wordsList = [
  "1 osoba nie resetuje OC",
  "2+ Judi",
  "2+ odpalone mapy",
  "Achivment za 10 hg",
  "Ale nikt nie callował by uderzać",
  "Auto-buy itemka za 5mil+",
  "Blink/dps w ścianę",
  "Bóg Heavy mace przeciwnik",
  "Bunto ginie pierwszy",
  "Curse przebija powietrze",
  "Daj Pov'a",
  "DC w teamie",
  "Dendro załamka",
  "Disband",
  "DPS bez mikro",
  "DPS w arkana",
  "Dyntka przez PK",
  "Gdzie mapa?",
  "Gdzie są defki",
  "Heal wskakuje w DPS",
  "Jak coś jest stream",
  "Jaka to była wyspa?",
  "Kajdany infamy",
  "Krecik robi samobója\n/\n Nie działają klawisze",
  "Lagi miałem",
  "Lawa",
  "Linka na Heal",
  "Mapa na broken fell",
  "Mele DPS się boi",
  "Nie da się zginąć",
  "Nie dało się",
  "Nie ma DPS",
  "Nie ma many",
  "Przerwali mi",
  "PVE party nas zabija",
  "Robimy nowe party",
  "Same zielone dzisiaj",
  "Sorry nie wiedziałem że mikro mute",
  "Spal ktoś mapę\n(cisza...)",
  "Stack 5+",
  "Szukamy jenego gracza",
  "Walka 4v4",
  "Wyjebanie się przez brak poty",
  "Zacznijcie mówić tymi dps",
  "Zagrajmy rycka bo się odbijam",
  "Zapomniane jedzenie / OC",
  "Zbugowana gra",
  "Zmieniamy compa",
  "Żarty o Rzymianach",
];
