export const wordsList = [
  "1 osoba nie resetuje OC",
  "2+ Judi",
  "2+ odpalone mapy",
  "Ale nikt nie callował by uderzać",
  "Auto-buy itemka za 5mil+",
  "Blink/dps w ścianę",
  "Bóg Heavy mace przeciwnik",
  "Bunto ginie pierwszy",
  "Dawajcie last OC",
  "Dendro załamka",
  "DPS bez mikro",
  "DPS w arkana",
  "Dyntka przez PK",
  "Gdzie jest mana?",
  "Gdzie mapa?",
  "Gdzie są defki",
  "Heal wskakuje w DPS",
  "Jak coś jest stream",
  "Krecik robi samobója\n/\n Nie działają klawisze",
  "Lagi miałem",
  "Linka na Heal",
  "Mapa na broken fell",
  "Mele DPS się boi",
  "Nie dało się",
  "Nie ma DPS",
  "Przerwali mi",
  "PVE party nam zabija",
  "Same zielone dzisiaj",
  "Sorry nie wiedziałem że mikro mute",
  "Spal ktoś mapę\n(cisza...)",
  "Stack 5+",
  "Wyjebanie się przez brak poty",
  "Zacznijcie mówić tymi dps",
  "Zagrajmy rycka bo się odbijam",
  "Zapomniane jedzenie / OC",
  "Żarty o Rzymianach ",
  "Zmieniamy compa",
];
