export const wordsList = [
  "Nie dało się",
  "Sorry nie wiedziałem że mikro mute",
  "Bunto ginie pierwszy",
  "Gdzie jest mana?",
  "Spal ktoś mapę\n(cisza...)",
  "Nie ma DPS",
  "Zacznijcie mówić tymi dps",
  "Zagrajmy rycka bo się odbijam",
  "Gdzie są defki",
  "Linka na Heal",
  "'Zmieniamy compa'",
  "Zapomniane jedzenie / OC",
  "1 osoba nie resetuje OC",
  "2+ Judi",
  "Gdzie mapa?",
  "2+ odpalone mapy",
  "DPS w arkana",
  "Mele DPS się boi",
  "Krecik robi samobója\n/\n Nie działają klawisze",
  "Lagi miałem",
  "Bóg Heavy mace przeciwnik",
  "Stack 5+",
  "Heal wskakuje w DPS",
  "'Same zielone dzisiaj'",
  "Żarty o Rzymianach ",
  "Jak coś jest stream",
  "Wyjebanie się przez brak poty",
  "PVE party nam zabija",
  "auto-buy itemka za 5mil+",
  "mapa na broken fell",
  "dyntka przez PK",
];
//  default wordsList;
// export default {
//   wordsList,
// };
