export const wordsList = [
  "1 osoba nie resetuje OC",
  "2+ Judi",
  "2+ odpalone mapy",
  "Achivment za 10 hg",
  "Auto-buy itemka za 5mil+",
  "Balkonik",
  "Blink/dps w ścianę",
  "Bóg Heavy mace przeciwnik",
  "Bunto ginie pierwszy",
  "Curse przebija powietrze",
  "Daj Pov'a",
  "Dawajcie last OC",
  "DC w teamie",
  "Dendro załamka",
  "Disband",
  "DPS bez mikro",
  "DPS pali losowe E",
  "DPS w arkana",
  "Dyntka przez PK",
  "Gdzie mapa?",
  "Gdzie są defki",
  "Heal wskakuje w DPS",
  "Jak coś jest stream",
  "Jaka to była wyspa?",
  "Kajdany infamy",
  "Krecik samobój\n/\n Nie działają klawisze",
  "Lagi miałem",
  "Lawa",
  "Linka na Heal",
  "Mapa na broken fell",
  "Melee DPS się boi",
  "Nie da się zginąć",
  "Nie dało się",
  "Nie ma DPS",
  "Nie ma many",
  "Przerwali mi",
  "PVE party nas zabija",
  "Resetujemy OC?",
  "Robimy nowe party",
  "Same zielone dzisiaj",
  "Sorry nie wiedziałem że mikro mute",
  "Spal ktoś mapę\n(cisza...)",
  "Stack 5+",
  "Szukamy jenego gracza",
  "Turysta w PT",
  "Udźwigu nie mam",
  "W kolejnym gate na pewno jest przeciwnik",
  "Walka 4v4",
  "Wyjebanie się przez brak poty",
  "Zacznijcie mówić tymi dps",
  "Zagrajmy rycka bo się odbijam",
  "Zamieszanie kto kogo zebrał",
  "Zapomniane jedzenie / OC",
  "Żarty o Rzymianach",
  "Zbugowana gra",
  "Zmieniamy compa",
  "Nietoperze za silne",
];
