# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js Deploy google cloud

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy ${{ github.event.repository.name }} using ssh
        # You may pin to the exact commit or the version.
        # uses: appleboy/ssh-action@334f9259f2f8eb3376d33fa4c684fff373f2c2a6
        uses: appleboy/ssh-action@master
        with:
          key: ${{secrets.GOOGLE_CLOUD_VM_SSH}}
          host: ${{secrets.GOOGLE_CLOUD_VM_IP}}
          username: ${{secrets.GOOGLE_CLOUD_VM_USERNAME}}
          script: |
            pm2 delete all
            cd /var/app/${{ github.event.repository.name }}/server
            git pull
            npm install
            # pm2 start npm --name "${{ github.event.repository.name }}" -- run start
            gcloud app deploy /var/app/${{ github.event.repository.name }}/server/app.yaml
            #publish to google cloud app engine
            # gcloud app deploy /var/app/${{ github.event.repository.name }}/server/app.yaml --project ${{secrets.GOOGLE_CLOUD_PROJECT_ID}}
